services:
  backend:
    build: .
    container_name: spring-app
    ports:
      - "8999:8999"
    environment:
      SPRING_PROFILES_ACTIVE: 'default'
      SPRING_DATASOURCE_URL: jdbc:mariadb://joayong-database.cxqg0uy8gnw9.ap-northeast-2.rds.amazonaws.com:3306/joayong
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dnwnrhdfyd12!
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
