server:
  port: 8999

# database setting
spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: riyo1753@naver.com
    password: PD3859M7XWCJ
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mariadb://localhost:3306/joayong
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true 
        type: trace

# log level setting
logging:
  level:
    root: info
    com:
      joayong:
        skillswap: debug  # 필요 시 trace로 변경 가능
    org:
      hibernate:
        SQL: debug      # SQL 쿼리 출력
        type: trace     # 바인딩 파라미터까지 출력
      springframework:
        web:
          socket: trace  # WebSocket 상세 디버깅
        messaging: trace # STOMP 메시지 디버깅
      stompjms: trace     # STOMP 프로토콜 디버깅 (SockJS/STOMP 관련)

# file upload setting
file:
  upload:
    location: ${user.home}/fish/uploads/

jwt:
  secret-key: L6h/xMxGO53HQmR/OB99qR/y0kTr2CAyaI5RqBIX184=  # 토큰발급시와 토큰위조검사시 사용할 서명
#  access-token-validity-time: 3600000  # 1시간 (ms)
  access-token-validity-time: 36000000  # 10시간 (ms)
  refresh-token-validity-time: 604800000 # 7일 (ms)
