name: Deploy Spring Application to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Make directory for deliver
        run: mkdir deploy

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Check directory contents
        run: ls -la build/libs/

      - name: Web Spring Boot Docker build and push
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build --no-cache -t cafephilia/joayong-api:latest .
          docker push cafephilia/joayong-api:latest

      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Docker login..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > ./docker-compose.yml
            docker-compose down || true
            docker rmi cafephilia/joayong-api:latest || true
            docker pull cafephilia/joayong-api:latest
            docker-compose up -d
